### ISSUE TITLE
Helm chart and index results merge conflict

### ISSUE THREAD

**Issue by yjian118** [Wind-River/cloud-platform-deployment-manager#156]
Helm chart and index between master and stable v2.0.10 results merge conflict if creat PR to get new commits, need to figure out the cause and standardize the process

**Comment by yjian118** [comment]
And a simple resolve of the merge conflicts may break the generation of the required helm chart.
Need comments from @enzocandotti and @ttakenak 
I'm thinking if we need to ignore the tracking of the helm chart as it is a tarball and not easy to resolv the conflicts, the index is fine though

**Comment by ttakenak** [comment]
I think we might need to track index and charts when we need to sync or cherry-pick between branches.
Personally I'd like to sync or cherry pick patch from other branch in local and regenerate helm charts in local and update index, then create PR. Because I'm a bit concern if helm charts includes the change which exists only one branch but no need to apply to the other branch (As CRDs are auto generated.)

**Comment by yjian118** [comment]
That's what I did last night to avoid the merge conflict. The index should definitely be tracked. @enzocandotti @hugonicodemos What's your opinion?

**Comment by yjian118** [comment]
As v2.0.10 is finalized, the new commits should be cherry-picked as standard operations. Close this issue.
